compliance/cis_eks/rules/cis_4_2_1/rule.rego, compliance/cis_eks/rules/cis_4_2_1/test.rego, compliance/cis_eks/rules/cis_4_2_2/rule.rego, compliance/cis_eks/rules/cis_4_2_2/test.rego, compliance/cis_eks/rules/cis_4_2_3/rule.rego, compliance/cis_eks/rules/cis_4_2_3/test.rego, compliance/cis_eks/rules/cis_4_2_4/rule.rego, compliance/cis_eks/rules/cis_4_2_4/test.rego, compliance/cis_eks/rules/cis_4_2_5/rule.rego, compliance/cis_eks/rules/cis_4_2_5/test.rego, compliance/cis_eks/rules/cis_4_2_6/rule.rego, compliance/cis_eks/rules/cis_4_2_6/test.rego, compliance/cis_eks/rules/cis_4_2_7/rule.rego, compliance/cis_eks/rules/cis_4_2_7/test.rego, compliance/cis_eks/rules/cis_4_2_8/rule.rego, compliance/cis_eks/rules/cis_4_2_8/test.rego, compliance/cis_eks/rules/cis_4_2_9/rule.rego, compliance/cis_eks/rules/cis_4_2_9/test.rego
This PR is related to - https://github.com/elastic/security-team/issues/3002.
In this PR we implemented the Kubernetes pod security policy rules.
Since they are almost identical to the vanilla one, almost no change was required.
- Closes: https://github.com/elastic/security-team/issues/3002
=> Adding-pod-security-policy-rules-for-EKS

compliance/cis_k8s/rules/cis_4_2_1/rule.rego, compliance/cis_k8s/rules/cis_4_2_1/test.rego, compliance/cis_k8s/rules/cis_4_2_2/rule.rego, compliance/cis_k8s/rules/cis_4_2_2/test.rego, compliance/cis_k8s/rules/cis_4_2_3/rule.rego, compliance/cis_k8s/rules/cis_4_2_3/test.rego, compliance/cis_k8s/rules/cis_4_2_6/rule.rego, compliance/cis_k8s/rules/cis_4_2_6/test.rego, compliance/cis_k8s/rules/cis_4_2_7/rule.rego, compliance/cis_k8s/rules/cis_4_2_7/test.rego, compliance/kubernetes_common/test_data.rego, compliance/lib/data_adapter.rego
This PR enables our Kubelet process rules, to support configuration file as an input.
Closes: https://github.com/elastic/security-team/issues/3279
=> Feature/vanilla-CSP-process -rules

compliance/cis_k8s/rules/cis_1_1_1/rule.rego, compliance/cis_k8s/rules/cis_1_1_11/rule.rego, compliance/cis_k8s/rules/cis_1_1_12/rule.rego, compliance/cis_k8s/rules/cis_1_1_13/rule.rego, compliance/cis_k8s/rules/cis_1_1_14/rule.rego, compliance/cis_k8s/rules/cis_1_1_15/rule.rego, compliance/cis_k8s/rules/cis_1_1_16/rule.rego, compliance/cis_k8s/rules/cis_1_1_17/rule.rego, compliance/cis_k8s/rules/cis_1_1_18/rule.rego, compliance/cis_k8s/rules/cis_1_1_19/rule.rego, compliance/cis_k8s/rules/cis_1_1_2/rule.rego, compliance/cis_k8s/rules/cis_1_1_3/rule.rego, compliance/cis_k8s/rules/cis_1_1_4/rule.rego, compliance/cis_k8s/rules/cis_1_1_5/rule.rego, compliance/cis_k8s/rules/cis_1_1_6/rule.rego, compliance/cis_k8s/rules/cis_1_1_7/rule.rego, compliance/cis_k8s/rules/cis_1_1_8/rule.rego, compliance/cis_k8s/rules/cis_4_1_1/rule.rego, compliance/cis_k8s/rules/cis_4_1_10/rule.rego, compliance/cis_k8s/rules/cis_4_1_2/rule.rego, compliance/cis_k8s/rules/cis_4_1_5/rule.rego, compliance/cis_k8s/rules/cis_4_1_9/rule.rego
Adding the first drop of the expected field to k8s rules (includes trivial rules).
This covers the GID/UID and permissions rules which are trivial to code.
Partially covers https://github.com/elastic/security-team/issues/3383
=> Addition of expected field to k8s rules

compliance/cis_k8s/rules/cis_1_1_1/rule.rego, compliance/cis_k8s/rules/cis_1_1_11/rule.rego, compliance/cis_k8s/rules/cis_1_1_13/rule.rego, compliance/cis_k8s/rules/cis_1_1_15/rule.rego, compliance/cis_k8s/rules/cis_1_1_17/rule.rego, compliance/cis_k8s/rules/cis_1_1_3/rule.rego, compliance/cis_k8s/rules/cis_1_1_5/rule.rego, compliance/cis_k8s/rules/cis_1_1_7/rule.rego, compliance/cis_k8s/rules/cis_4_1_1/rule.rego, compliance/cis_k8s/rules/cis_4_1_5/rule.rego, compliance/cis_k8s/rules/cis_4_1_9/rule.rego
Making sure that expected is aligned to evidence and returns the permissions as strings and not numbers
=> Rule expected permissions as string instead of number

compliance/cis_eks/rules/cis_3_2_7/rule.rego, compliance/cis_eks/rules/cis_3_2_7/test.rego, compliance/cis_k8s/rules/cis_1_2_23/rule.rego, compliance/cis_k8s/rules/cis_4_2_7/rule.rego, compliance/cis_k8s/rules/cis_4_2_7/test.rego
* fixed : https://github.com/elastic/csp-security-policies/issues/90
Whenever there is no `--make-iptables-util-chains` process flag the rule should pass
=> CSP-48-cis-4.2.7-fix default value

compliance/cis_k8s/rules/cis_5_1_5/rule.rego, compliance/cis_k8s/rules/cis_5_1_6/rule.rego, compliance/kubernetes_common/test_data.rego, compliance/lib/data_adapter/data_adapter.rego
Kube objects type was updated in Cloudbeat to `k8s_object` but the data adapter was not, this led to some kube rules not filtering correctly and in turn not running at all
____
- Closing: https://github.com/elastic/security-team/issues/4169
=> Update data_adapter kube-api filtering 

compliance/main.rego
Compliance had multiple non-unique values (cis_k8s twice), thus evaluated twice and this is the reason why we've had more findings than expected.
Still investigating the reason why adding YAML files under rule directories creates a duplicate in the compliance import value for the benchmarks.
Another way to resolve this issue is by assuring uniqueness via Set.
```
rego := {x | x = compliance[benchmarks]}
```
Fixes - https://github.com/elastic/cloudbeat/issues/219
Opened - https://github.com/open-policy-agent/opa/issues/4787
=> Duplicate benchmark loop fix

cis_policies_generator/config/default.json, cis_policies_generator/src/fixBrokenReferences.ts, cis_policies_generator/src/index.ts, cis_policies_generator/src/types.d.ts, cis_policies_generator/tsconfig.json
relates https://github.com/elastic/security-team/issues/4479
=> Remove broken refs

bundle/compliance/cis_eks/rules/cis_3_1_1/rule.rego, bundle/compliance/cis_eks/rules/cis_3_1_3/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_1/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_11/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_13/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_15/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_17/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_20/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_21/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_3/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_5/rule.rego, bundle/compliance/cis_k8s/rules/cis_1_1_7/rule.rego, bundle/compliance/cis_k8s/rules/cis_4_1_1/rule.rego, bundle/compliance/cis_k8s/rules/cis_4_1_5/rule.rego, bundle/compliance/cis_k8s/rules/cis_4_1_9/rule.rego, bundle/compliance/policy/file/common.rego, bundle/compliance/policy/file/common_test.rego, bundle/compliance/policy/file/ensure_permissions.rego
We've had a problem when we wanted to verify exact permissions because we've always checked permissions that are equal or more restrictive.
Fixes:
- #132
=> File permissions checks fix for exact permissions

.github/workflows/test-policies.yml
The latest image of OPA is broken and doesn't have diff in PATH.
Due to this, the CI doesn't pass.
Changed to work with a fixed version in order to avoid such cases in the future.
=> Assign fixed version for OPA in the CI

.github/workflows/test-policies.yml
We've decided to roll back and still use OPA's latest version for all of the checks.
Only leave the fmt with the working last working version.
=> Rolling back OPA version to latest, besides fmt that fails on latest

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_2_1_2/data.yaml, bundle/compliance/cis_aws/rules/cis_2_1_2/rule.rego, bundle/compliance/cis_aws/rules/cis_2_1_2/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_3/data.yaml, bundle/compliance/cis_aws/rules/cis_2_1_3/rule.rego, bundle/compliance/cis_aws/rules/cis_2_1_3/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_s3/data_adapter.rego, bundle/compliance/policy/aws_s3/ensure_bucket_policy_deny_http.rego, bundle/compliance/policy/aws_s3/ensure_mfa_delete_enabled.rego
Implement two additional rules for AWS CIS S3 section:
- 2.1.2 Ensure S3 Bucket Policy is set to deny HTTP requests
- 2.1.3 Ensure MFA Delete is enabled on S3 buckets
Resolves https://github.com/elastic/csp-security-policies/issues/144
`cloudbeat` PR: https://github.com/elastic/cloudbeat/pull/661
=> Implement more AWS CIS S3 rules

bundle/compliance/cis_eks/data_adapter.rego, bundle/compliance/cis_eks/rules/cis_3_2_4/test.rego, bundle/compliance/cis_eks/rules/cis_3_2_5/test.rego, bundle/compliance/cis_eks/rules/cis_3_2_7/test.rego, bundle/compliance/cis_k8s/data_adapter.rego, bundle/compliance/policy/process/data_adapter.rego
arg parser will now support both `=` and space diameter 
- Fixes: https://github.com/elastic/cloudbeat/issues/632
- Fixes: https://github.com/elastic/cloudbeat/issues/633
- Fixes: https://github.com/elastic/cloudbeat/issues/631
=> Fix arg parser

bundle/compliance/cis_eks/rules/cis_4_2_7/test.rego, bundle/compliance/cis_k8s/rules/cis_5_2_8/test.rego, bundle/compliance/policy/kube_api/data_adapter.rego, bundle/compliance/policy/kube_api/minimize_certain_capability.rego
Update the audit function's filter to apply only to pod resources.
The previous implementation accidentally filtered events the right way by the evidence section.
Affected rules: 
- CIS EKS 4.2.7
- CIS K8s 5.2.8
- https://github.com/elastic/csp-security-policies/pull/184
=> Update minimize_certain_capability audit function

bundle/compliance/cis_aws/rules/cis_2_1_2/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_s3/data_adapter.rego, bundle/compliance/policy/aws_s3/ensure_bucket_policy_deny_http.rego
Handle the case in which we are sending s3 buckets with empty policy statements for evaluation causing `eval_conflict_error`.
- Fixes: https://github.com/elastic/csp-security-policies/issues/198
=> Fix evaluation conflict in s3 data adapter

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_2_1_1/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_2/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_3/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_5/data.yaml, bundle/compliance/cis_aws/rules/cis_2_1_5/rule.rego, bundle/compliance/cis_aws/rules/cis_2_1_5/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_s3/data_adapter.rego, bundle/compliance/policy/aws_s3/ensure_block_public_access.rego
Add CIS AWS S3 rule 2.1.5 - Ensure that S3 Buckets are configured with 'Block public access (bucket settings)'
Resolves https://github.com/elastic/csp-security-policies/issues/194
=> Add CIS AWS S3 rule 2.1.5

bundle/compliance/cis_aws/rules/cis_2_1_1/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_2/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_3/test.rego, bundle/compliance/cis_aws/rules/cis_2_1_5/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_s3/data_adapter.rego, bundle/compliance/policy/aws_s3/ensure_block_public_access.rego
Fix the implementation of CIS AWS rule 2.1.5 - Ensure that S3 Buckets are configured with 'Block public access (bucket settings)'
Related https://github.com/elastic/csp-security-policies/issues/194
=> Fix CIS AWS rule 2.1.5

bundle/compliance/cis_aws/rules/cis_3_6/rule.rego, bundle/compliance/cis_aws/test_data.rego
Fix CIS AWS rule 3.6 - Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket
Resolves https://github.com/elastic/cloudbeat/issues/810
=> Fix CIS AWS rule 3.6

bundle/compliance/cis_aws/rules/cis_5_4/test.rego, bundle/compliance/policy/aws_ec2/data_adapter.rego, bundle/compliance/policy/aws_ec2/ensure_default_security_group_restricted.rego
Making sure that AWS CIS rule 5.4 doesn't evaluate non-default resources.
Ran evaluation comand:
```bash
opa eval -b ./bundle -i input_securitygroup.json data.main
```
With input:
```json
{
"subType": "aws-security-group",
"resource": {
"GroupName": "jenia",
"IpPermissions": [
{
"FromPort": 22,
"IpProtocol": "tcp",
"IpRanges": [
{
"CidrIp": ""
}
]
}
],
"IpPermissionsEgress": [
{
"IpProtocol": "-1",
"IpRanges": [
{
"CidrIp": ""
}
]
}
]
}
}
```
Got response:
```json
{
"result": [
{
"expressions": [
{
"value": {
"findings": [
{
"result": {
"evaluation": "passed",
"evidence": {
"GroupName": "jenia",
"IpPermissions": [
{
"FromPort": 22,
"IpProtocol": "tcp",
"IpRanges": [
{
"CidrIp": ""
}
]
}
],
"IpPermissionsEgress": [
{
"IpProtocol": "-1",
"IpRanges": [
{
"CidrIp": ""
}
]
}
]
}
},
"rule": { …
```
=> Fixing security group non default evaluations

bundle/compliance/cis_aws/rules/cis_3_10/test.rego, bundle/compliance/cis_aws/rules/cis_3_11/test.rego, bundle/compliance/policy/aws_cloudtrail/verify_s3_object_logging.rego
Fixing CSPM rules 3.10, 3.11.
When object-level logging for write / read events is enabled for S3 bucket the evaluation should pass.
Resolves: https://github.com/elastic/cloudbeat/issues/811
=> Fix bug of Object-level logging for S3 buckets

bundle/compliance/cis_aws/rules/cis_4_1/rule.rego, bundle/compliance/cis_aws/rules/cis_4_1/test.rego
Fix CIS 4.1 pattern: The wildcard `*` characters were missing
- Related: https://github.com/elastic/cloudbeat/issues/823
=> Fix CIS 4.1 pattern

bundle/compliance/cis_aws/rules/cis_4_1/test.rego, bundle/compliance/cis_aws/rules/cis_4_10/test.rego, bundle/compliance/cis_aws/rules/cis_4_11/test.rego, bundle/compliance/cis_aws/rules/cis_4_12/test.rego, bundle/compliance/cis_aws/rules/cis_4_13/test.rego, bundle/compliance/cis_aws/rules/cis_4_14/test.rego, bundle/compliance/cis_aws/rules/cis_4_15/test.rego, bundle/compliance/cis_aws/rules/cis_4_2/test.rego, bundle/compliance/cis_aws/rules/cis_4_3/test.rego, bundle/compliance/cis_aws/rules/cis_4_4/test.rego, bundle/compliance/cis_aws/rules/cis_4_5/test.rego, bundle/compliance/cis_aws/rules/cis_4_6/test.rego, bundle/compliance/cis_aws/rules/cis_4_7/test.rego, bundle/compliance/cis_aws/rules/cis_4_8/test.rego, bundle/compliance/cis_aws/rules/cis_4_9/test.rego, bundle/compliance/policy/aws_cloudtrail/pattern.rego, bundle/compliance/policy/aws_cloudtrail/pattern_test.rego, bundle/compliance/policy/aws_cloudtrail/trail.rego
Fix the bug that happens when multiple trails exist, but only some are configured with an alarm and SNS topic to cause passing findings. 
This way we make sure that the sns topic is configured with the require metric filter
- https://github.com/elastic/cloudbeat/pull/846
- https://github.com/elastic/cloudbeat/issues/826
=> fix: validate required filter pattern having topic

bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_cloudtrail/ensure_cloudwatch_integration.rego
There was a misspelling in the code on fields that were checked.
The resource that was used for validation:
```json
{
"subType": "aws-trail",
"resource": {
"Status": {
"LatestCloudWatchLogsDeliveryTime": "2023-03-04T16:09:47.346000+03:00"
},
"Trail": {
"CloudWatchLogsLogGroupArn": "jenia"
}
}
}
```
Getting a failed finding:
```json
{
"result": {
"evaluation": "failed",
"evidence": {
"Status": {
"LatestCloudWatchLogsDeliveryTime": "2023-02-04T16:09:47.346000+03:00"
},
"Trail": {
"CloudWatchLogsLogGroupArn": "jenia"
}
}
},
"rule": {
"audit": "Perform the following to ensure CloudTrail is configured as prescribed:\n\n**From Console:**\n\n1. Login to the CloudTrail console at `https://console.aws.amazon.com/cloudtrail/`\n2. Under `Trails` , click on the CloudTrail you wish to evaluate\n3. …
```
=> Fixing CIS AWS cloudtrail rule 3.4

bundle/compliance/cis_eks/rules/cis_3_2_5/rule.rego, bundle/compliance/cis_eks/rules/cis_3_2_5/test.rego
fail the rule if the value of `--streaming-connection-idle-timeout` or `streamingConnectionIdleTimeout` is `"0s"`, `"0"` or `0` 
| ![Screenshot 2023-04-23 at 14 00 48](https://user-images.githubusercontent.com/20814186/233836114-bf3d8901-d721-4304-abe1-5f8a394eb354.png) | ![Screenshot 2023-04-23 at 14 01 14](https://user-images.githubusercontent.com/20814186/233836091-dad0112d-8339-4155-8f13-b5525807f1f8.png) |
|---------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|
- closes: https://github.com/elastic/cloudbeat/issues/632
> **Note** Make sure to bump cloudbeat …
=> Fix CIS EKS 3.2.5

bundle/compliance/cis_aws/rules/cis_2_1_5/test.rego, bundle/compliance/policy/aws_s3/ensure_block_public_access.rego
Fix CIS AWS rule 2.1.5 so it can handle missing account/bucket level public access block configuration.
Fixes #233
=> CIS AWS rule 2.1.5 can now handle missing public block config

bundle/compliance/cis_k8s/rules/cis_1_1_19/test.rego
Complimentary of https://github.com/elastic/cloudbeat/pull/981
The test is not really necessary but it doesn't hurt to have it as a future guard for breaking changes.
=> Add tests for recursive pki/ directories

bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego
this changes existing rules to not reference `resource.asset` as we removed it
=> [GCP] Use new resource interface

.github/workflows/rule-status.yml, .pre-commit-config.yaml
this PR introduces a new workflow that will generate `RULES.md` and `README.md` pre-merge by calling `poetry run python dev/update_rule_status.py` and update the PR 
1 - [doesn't commit when there are no changes: ](https://github.com/elastic/csp-security-policies/actions/runs/5665953337/job/15351714162?pr=262)
2 - [commits when there are changes](https://github.com/orouz/csp-security-policies/actions/runs/5665864941/job/15351453008?pr=13)  (note: this workflow is slightly different because it's on a fork)
looks like this:
=> Add a workflow to generate markdown files

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_15/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_15/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_15/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 1.15
| failed (api key not within last 90 days) |  passed (api key not within last 90 days)  |
| can't set past date for api key, covered in tests | <img width="454" alt="Screenshot 2023-08-01 at 14 35 28" src="https://github.com/elastic/csp-security-policies/assets/20814186/1a27d0b8-3696-445c-b70a-34579e487c93">|
=> Add CIS 1.15

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_12/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_12/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_12/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 1.12
| failed (project level api key) |  passed (api key not on project level )  |
| <img width="534" alt="Screenshot 2023-08-01 at 15 00 17" src="https://github.com/elastic/csp-security-policies/assets/20814186/beac48e7-92b1-4a18-bd45-0ba3c5856e96"> |  my user can't add org key, and there aren't any in our gcp account |
=> Add CIS 1.12

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_6_1_3/data.yaml, bundle/compliance/cis_gcp/rules/cis_6_1_3/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_1_3/test.rego
Adds CIS GCP 6.1.3
| failed (`local_infile` is on) |  passed (`local_infile` is off)  |
| <img width="1315" alt="Screenshot 2023-08-13 at 13 15 47" src="https://github.com/elastic/csp-security-policies/assets/20814186/e0366b2f-24f1-425d-b383-bed72b21b1a7"> - |
- 
=> Add CIS GCP 6.1.3

bundle/compliance/cis_gcp/rules/cis_1_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_6/test.rego
this PR fixes a rule 1.6 subtype. using the wrong one, this rule ended up [not evaluating](https://github.com/elastic/cloudbeat/issues/672#issuecomment-1697318129) iam-policies.
=> [GCP] Fix 1.6 subtype

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_2_2/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_2/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_2/test.rego, bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego
This rule is tricky.
The evaluated asset is an array of log sinks, consisting of those configured specifically for a single project, as well as those configured at higher levels (folders and organization).
This approach ensures that even if a log sink is configured at a higher level than a project, the project is covered, and the rule should still pass.
- #305 
=> [CIS GCP] Implement rule 2.2 - Log Sinks

bundle/compliance/cis_azure/test_data.rego, bundle/compliance/policy/azure/data_adapter.rego
Rename the field because of https://github.com/elastic/cloudbeat/pull/1385
=> activity_log_alerts: Change to array in resource level

bundle/compliance/cis_azure/rules/cis_3_10/test.rego, bundle/compliance/cis_azure/rules/cis_3_2/test.rego, bundle/compliance/cis_azure/rules/cis_3_7/test.rego, bundle/compliance/policy/azure/storage_account/ensure_connection.rego, bundle/compliance/policy/azure/storage_account/ensure_encryption.rego, bundle/compliance/policy/azure/storage_account/ensure_public_access.rego
After the QA cycle, we've found storage account rules issues.
This PR addresses these issues and fixes them.
- Related: https://github.com/elastic/cloudbeat/issues/1254
=> Fixing storage account rules after QA cycle

bundle/compliance/cis_azure/rules/cis_9_4/rule.rego, bundle/compliance/cis_azure/rules/cis_9_4/test.rego
We've decided to change the checked property after reading the description and the actual rule.
The previous implementation followed the CIS remediation and Azure's implementation.
- Related: https://github.com/elastic/cloudbeat/issues/1259
=> Azure rule 9.4 property change
