.github/workflows/test-coverage.yml
=> fix coverage yml

README.md, compliance/cis_k8s/schemas/input_schema.json, compliance/kubernetes_common/test_data.rego, compliance/lib/data_adapter/data_adapter.rego
Update FS type from `file-system` to `file`
=> Update data adapter with new FS type

compliance/cis_k8s/rules/cis_1_3_2/rule.rego, compliance/cis_k8s/rules/cis_1_3_2/test.rego, compliance/cis_k8s/rules/cis_1_3_3/rule.rego, compliance/cis_k8s/rules/cis_1_3_3/test.rego, compliance/cis_k8s/rules/cis_1_3_4/rule.rego, compliance/cis_k8s/rules/cis_1_3_4/test.rego, compliance/cis_k8s/rules/cis_1_3_5/rule.rego, compliance/cis_k8s/rules/cis_1_3_5/test.rego, compliance/cis_k8s/rules/cis_1_3_6/rule.rego, compliance/cis_k8s/rules/cis_1_3_6/test.rego, compliance/cis_k8s/rules/cis_1_3_7/rule.rego, compliance/cis_k8s/rules/cis_1_3_7/test.rego, compliance/lib/data_adapter/data_adapter.rego
Kube controller manager process rules were not running due to a mistake in the process name.
Issue https://github.com/elastic/cloudbeat/issues/111
=> Run kube controller manger rules

bundle/compliance/cis_eks/rules/cis_3_2_9/rule.rego, bundle/compliance/cis_eks/rules/cis_3_2_9/test.rego
- Fixes: https://github.com/elastic/cloudbeat/issues/284
=> fixing rule 3_2_9

README.md, bundle/builder.go, bundle/compliance/cis_eks/cis_eks.rego, bundle/compliance/cis_k8s/cis_k8s.rego, bundle/compliance/main.rego
Ticket:
- https://github.com/elastic/security-team/issues/4452
Related cloudbeat task and PR:
- https://github.com/elastic/cloudbeat/pull/322
- https://github.com/elastic/security-team/issues/4497
=> Pass activated rules as an input 

bundle/compliance/cis_k8s/rules/cis_4_2_10/data.yaml
Fixes https://github.com/elastic/cloudbeat/issues/227
=> Remove comma from rule id

bundle/compliance/lib/data_adapter/data_adapter.rego
relates
- https://github.com/elastic/security-team/issues/4456
=> Remove from common data adapter

bundle/compliance/cis_eks/rules/cis_3_1_3/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_10/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_11/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_4/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_5/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_8/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_9/data.yaml, bundle/compliance/cis_eks/rules/cis_3_2_9/rule.rego, bundle/compliance/cis_eks/rules/cis_3_2_9/test.rego, bundle/compliance/lib/output_validations/output_validations.rego
- Fixes: https://github.com/elastic/csp-security-policies/issues/110
=> updating eks schema validation

bundle/compliance/cis_k8s/rules/cis_5_2_2/test.rego, bundle/compliance/policy/kube_api/data_adapter.rego, bundle/compliance/policy/kube_api/minimize_admission.rego, bundle/compliance/policy/kube_api/minimize_admission_root.rego, bundle/compliance/policy/kube_api/minimize_assigned_capabilities.rego
**Description**
- Handles the issues we had with pods with both `containers` and `initContainers`
- Adds tests that fail in the previous state
- Refactored some evidence collection for some of the relevant rules 
____
- fixes: https://github.com/elastic/cloudbeat/issues/316
=> fix multi container input issues

README.md, RULES.md, dev/update_rule_status.py
Rules implementations status improvements:
> **Note** Make sure to bump cloudbeat `go.mod` after merging this PR.
=> rules status automation improvements

.pre-commit-config.yaml, README.md, bundle/compliance/main.rego
Removing runtime config and activated rules from main.
Now we either run all rules of specific benchmarks or run all benchmarks.
> **Note** Make sure to bump cloudbeat `go.mod` after merging this PR.
=> Remove runtime config

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_5_1/data.yaml, bundle/compliance/cis_aws/rules/cis_5_1/rule.rego, bundle/compliance/cis_aws/rules/cis_5_1/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_ec2/data_adapter.rego, bundle/compliance/policy/aws_ec2/ensure_public_ingress.rego, bundle/compliance/policy/aws_ec2/ports.rego, bundle/compliance/policy/aws_ec2/ports_test.rego
Add CIS AWS networking rule 
- https://github.com/elastic/csp-security-policies/issues/149
- https://github.com/elastic/cloudbeat/pull/595
- closes: https://github.com/elastic/csp-security-policies/issues/149
=> feat: add cis aws 5.1 rule

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/issue_template.md
Updating the issue template to use the new team label `Team:Cloud Security` instead of `Team:Cloud Security Posture`
> **Note** Make sure to bump cloudbeat `go.mod` after merging this PR.
=> [Cloud Security] Updating team label

.github/workflows/test-policies.yml, README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_5_2/data.yaml, bundle/compliance/cis_aws/rules/cis_5_2/rule.rego, bundle/compliance/cis_aws/rules/cis_5_2/test.rego, bundle/compliance/cis_aws/rules/cis_5_3/data.yaml, bundle/compliance/cis_aws/rules/cis_5_3/rule.rego, bundle/compliance/cis_aws/rules/cis_5_3/test.rego, bundle/compliance/cis_aws/rules/cis_5_4/data.yaml, bundle/compliance/cis_aws/rules/cis_5_4/rule.rego, bundle/compliance/cis_aws/rules/cis_5_4/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_ec2/data_adapter.rego, bundle/compliance/policy/aws_ec2/ensure_default_security_group_restricted.rego, bundle/compliance/policy/aws_ec2/ensure_public_ingress.rego, bundle/compliance/policy/aws_ec2/ensure_security_group_public_ingress_ipv4.rego, bundle/compliance/policy/aws_ec2/ensure_security_group_public_ingress_ipv6.rego
- Related https://github.com/elastic/csp-security-policies/issues/149
- https://github.com/elastic/cloudbeat/pull/637
=> feat: add cis aws networking rules

RULES.md, dev/update_rule_status.py, poetry.lock, pyproject.toml
Splitting the automated/manual rules percentage
=> split automated/manual percentage

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_1_15/data.yaml, bundle/compliance/cis_aws/rules/cis_1_15/rule.rego, bundle/compliance/cis_aws/rules/cis_1_15/test.rego, bundle/compliance/cis_aws/test_data.rego
Add rule 1.15 of CIS AWS
- Related: https://github.com/elastic/cloudbeat/pull/660
> **Note** Make sure to bump cloudbeat `go.mod` after merging this PR.
=> Add rule 1.15 of CIS AWS

bundle/compliance/cis_eks/rules/cis_4_2_9/test.rego, bundle/compliance/cis_k8s/rules/cis_5_2_10/test.rego, bundle/compliance/policy/kube_api/minimize_assigned_capabilities.rego
Fix cis k8s 5.2.10 and cis eks 4.2.9
Before and after the fix
- Fixes: https://github.com/elastic/cloudbeat/issues/636
Input example
```json
{
"subType": "Pod",
"name": "pod-84c8b475f-w9ckf",
"resource": {
"metadata": {
"name": "pod-84c8b475f-w9ckf",
"namespace": "default"
},
"apiVersion": "v1",
"kind": "Pod",
"spec": {
"nodeName": "kind-multi-worker",
"containers": [
{
"name": "alpine",
"securityContext": {
"capabilities": {
"drop": [
"ALL"
]
}
}
}
]
}
},
"type": "k8s_object"
}
```
=> fix: cis_k8s 5.2.10, cis_eks 4.2.9

bundle/compliance/cis_eks/rules/cis_4_2_7/test.rego, bundle/compliance/cis_k8s/rules/cis_5_2_8/test.rego, bundle/compliance/kubernetes_common/test_data.rego, bundle/compliance/policy/kube_api/minimize_certain_capability.rego
Fix the implementation of the following rules:
EKS: 4.2.7
K8s: 5.2.8
- Related: https://github.com/elastic/cloudbeat/pull/689
=> Fix implementation of rules eks_cis_4.2.7 and k8s_cis_5.2.8

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_3_1/data.yaml, bundle/compliance/cis_aws/rules/cis_3_1/rule.rego, bundle/compliance/cis_aws/rules/cis_3_1/test.rego, bundle/compliance/cis_aws/rules/cis_4_1/rule.rego, bundle/compliance/cis_aws/rules/cis_4_10/rule.rego, bundle/compliance/cis_aws/rules/cis_4_11/rule.rego, bundle/compliance/cis_aws/rules/cis_4_12/rule.rego, bundle/compliance/cis_aws/rules/cis_4_13/rule.rego, bundle/compliance/cis_aws/rules/cis_4_14/rule.rego, bundle/compliance/cis_aws/rules/cis_4_15/rule.rego, bundle/compliance/cis_aws/rules/cis_4_2/rule.rego, bundle/compliance/cis_aws/rules/cis_4_3/rule.rego, bundle/compliance/cis_aws/rules/cis_4_4/rule.rego, bundle/compliance/cis_aws/rules/cis_4_5/rule.rego, bundle/compliance/cis_aws/rules/cis_4_6/rule.rego, bundle/compliance/cis_aws/rules/cis_4_7/rule.rego, bundle/compliance/cis_aws/rules/cis_4_8/rule.rego, bundle/compliance/cis_aws/rules/cis_4_9/rule.rego, bundle/compliance/policy/aws_cloudtrail/data_adapter.rego, bundle/compliance/policy/aws_cloudtrail/trail.rego
Add CIS AWS 3.1 rule 
- Related https://github.com/elastic/csp-security-policies/issues/147
=> aws cis 3 1

bundle/compliance/cis_k8s/rules/cis_4_2_10/data.yaml, bundle/compliance/cis_k8s/rules/cis_5_1_3/data.yaml, dev/generate_rule_metadata.py
- Replace empty default values
=> Replace empty default values

bundle/compliance/cis_aws/rules/cis_3_1/rule.rego, bundle/compliance/cis_aws/rules/cis_4_1/rule.rego, bundle/compliance/cis_aws/rules/cis_4_10/rule.rego, bundle/compliance/cis_aws/rules/cis_4_11/rule.rego, bundle/compliance/cis_aws/rules/cis_4_12/rule.rego, bundle/compliance/cis_aws/rules/cis_4_13/rule.rego, bundle/compliance/cis_aws/rules/cis_4_14/rule.rego, bundle/compliance/cis_aws/rules/cis_4_15/rule.rego, bundle/compliance/cis_aws/rules/cis_4_2/rule.rego, bundle/compliance/cis_aws/rules/cis_4_3/rule.rego, bundle/compliance/cis_aws/rules/cis_4_4/rule.rego, bundle/compliance/cis_aws/rules/cis_4_5/rule.rego, bundle/compliance/cis_aws/rules/cis_4_6/rule.rego, bundle/compliance/cis_aws/rules/cis_4_7/rule.rego, bundle/compliance/cis_aws/rules/cis_4_8/rule.rego, bundle/compliance/cis_aws/rules/cis_4_9/rule.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_cloudtrail/data_adapter.rego
Update monitoring rules filter to be the new monitoring resource's sub-type - `aws-multi-trails`.
- Related: https://github.com/elastic/cloudbeat/pull/761
- Fixes: https://github.com/elastic/security-team/issues/6051
=> Modify monitoring rules filter

bundle/compliance/cis_aws/rules/cis_1_12/test.rego, bundle/compliance/policy/aws_iam/validate_credentials.rego
Fix CIS AWS rule 1.12 - Ensure credentials unused for 45 days or greater are disabled
Resolves https://github.com/elastic/csp-security-policies/issues/202
=> Fix CIS AWS rule 1.12

bundle/compliance/cis_aws/rules/cis_4_4/rule.rego, bundle/compliance/cis_aws/rules/cis_4_4/test.rego
Fix CIS 4.4 pattern: Some spaces seemed to be in the pattern, probably from a copy-paste error.
- Related: https://github.com/elastic/cloudbeat/issues/827
=> Fix CIS 4.4 pattern

README.md
=> README: Fix command to test specific rule

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_3_5/data.yaml, bundle/compliance/cis_aws/rules/cis_3_5/rule.rego, bundle/compliance/cis_aws/rules/cis_3_5/test.rego, bundle/compliance/cis_aws/test_data.rego, bundle/compliance/policy/aws_config/data_adapter.rego, bundle/compliance/policy/aws_config/ensure_config_enabled.rego
Adds rule 3.5 of CIS AWS 
- closes https://github.com/elastic/csp-security-policies/issues/188
=> Add CIS AWS 3.5 rule

README.md, RULES.md, bundle/compliance/cis_aws/rules/cis_1_17/data.yaml, bundle/compliance/cis_aws/rules/cis_1_17/rule.rego, bundle/compliance/cis_aws/rules/cis_1_17/test.rego, bundle/compliance/policy/aws_iam/data_adapter.rego
Implement CIS AWS rule 1.17
- Fixes: https://github.com/elastic/csp-security-policies/issues/220
- https://github.com/elastic/cloudbeat/pull/877
=> Implement CIS AWS rule 1.17

bundle/compliance/cis_aws/rules/cis_1_20/rule.rego, bundle/compliance/cis_aws/rules/cis_1_20/test.rego, bundle/compliance/policy/aws_iam/data_adapter.rego
See https://github.com/elastic/cloudbeat/pull/916
- https://github.com/elastic/csp-security-policies/issues/222
- https://github.com/elastic/cloudbeat/pull/916
=> AWS CIS 1.20: Use array instead of map

bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego
this adds utilities used in other rules (currently duplicated in multiple PRs)
=> [GCP] Add iam rules utilities

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_6/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_6/test.rego, bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/iam/ensure_role_not_service_account_user.rego
=> [GCP] Add CIS 1.6

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_5/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_5/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_5/test.rego, bundle/compliance/policy/gcp/iam/ensure_user_not_editor_or_owner.rego
Adds CIS 1.5
| failed|  passed  |
| <img width="520" alt="Screenshot 2023-07-18 at 15 44 57" src="https://github.com/elastic/csp-security-policies/assets/20814186/acced92f-3b14-42bd-81b6-17258b735b1d"> | <img width="563" alt="Screenshot 2023-07-18 at 15 44 41" src="https://github.com/elastic/csp-security-policies/assets/20814186/8335cfbd-66bd-481b-a9a3-db82d8964a2e"> | 
=> [GCP] Add CIS 1.5

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_4/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_4/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_4/test.rego, bundle/compliance/policy/gcp/iam/ensure_policy_not_managed_by_user.rego
=> Add CIS 1.4

bundle/compliance/cis_gcp/rules/cis_1_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_6/test.rego, bundle/compliance/cis_gcp/test_data.rego
replaces iteration in function param to a value 
=> Fix CIS GCP 1.6

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_3_3/data.yaml, bundle/compliance/cis_gcp/rules/cis_3_3/rule.rego, bundle/compliance/cis_gcp/rules/cis_3_3/test.rego, bundle/compliance/cis_gcp/rules/cis_3_4/data.yaml, bundle/compliance/cis_gcp/rules/cis_3_4/rule.rego, bundle/compliance/cis_gcp/rules/cis_3_4/test.rego, bundle/compliance/cis_gcp/rules/cis_3_5/data.yaml, bundle/compliance/cis_gcp/rules/cis_3_5/rule.rego, bundle/compliance/cis_gcp/rules/cis_3_5/test.rego, bundle/compliance/policy/gcp/data_adapter.rego, bundle/compliance/policy/gcp/dns/ensure_rsasha1_is_unused.rego
Implement rules 3.3-3.5 (dns)
- Related: https://github.com/elastic/cloudbeat/pull/1196
=> [CIS GCP] Implement Cloud DNS rules

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_11/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_11/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_11/test.rego, bundle/compliance/policy/gcp/data_adapter.rego, bundle/compliance/policy/gcp/iam/ensure_admin_without_multiple_roles.rego
Adds CIS 1.11
| failed (same user both admin and other role) |  passed (user doesn't have both admin and other role)  |
| <img width="671" alt="Screenshot 2023-08-02 at 16 00 09" src="https://github.com/elastic/csp-security-policies/assets/20814186/76bc5a5f-eaa4-4adb-b129-fabb6163a4d3"> | <img width="670" alt="Screenshot 2023-08-02 at 16 02 17" src="https://github.com/elastic/csp-security-policies/assets/20814186/61c483ca-d995-4cd5-8ef1-b1785168e7a8"> |
=> Add CIS 1.11

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_14/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_14/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_14/test.rego
Adds CIS GCP 1.14
| failed (restrictions on `cloudapis.googleapis.com`) |  passed (no restrictions on `cloudapis.googleapis.com`)  |
| AFAIK editing api keys doesn't allow adding this restriction |  <img width="433" alt="Screenshot 2023-08-01 at 15 31 04" src="https://github.com/elastic/csp-security-policies/assets/20814186/e6df7c23-f46a-43df-9703-f9379a980072">|
=> Add CIS 1.14

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_2_10/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_10/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_10/test.rego, bundle/compliance/cis_gcp/rules/cis_2_11/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_11/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_11/test.rego, bundle/compliance/cis_gcp/rules/cis_2_4/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_4/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_4/test.rego, bundle/compliance/cis_gcp/rules/cis_2_5/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_5/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_5/test.rego, bundle/compliance/cis_gcp/rules/cis_2_6/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_6/test.rego, bundle/compliance/cis_gcp/rules/cis_2_7/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_7/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_7/test.rego, bundle/compliance/cis_gcp/rules/cis_2_8/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_8/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_8/test.rego, bundle/compliance/cis_gcp/rules/cis_2_9/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_9/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_9/test.rego, bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego, bundle/compliance/policy/gcp/monitoring/ensure_log_metric_and_alarm_exist.rego
Implement rules 2.4-2.11, ensures combination of log metric and policy alarm.
- Related: https://github.com/elastic/csp-security-policies/issues/240
=> [CIS GCP] Implement monitoring rules

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_8/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_8/test.rego
Adds CIS GCP 1.8
| failed (same user both admin and user role) |  passed (user doesn't have both admin and user role)  |
| <img width="550" alt="Screenshot 2023-07-31 at 15 10 53" src="https://github.com/elastic/csp-security-policies/assets/20814186/667d7dbc-93cc-4e93-9513-25b92d5ede3f">  | <img width="491" alt="Screenshot 2023-07-31 at 15 11 07" src="https://github.com/elastic/csp-security-policies/assets/20814186/1e06f7d8-d204-4a20-b259-9b6a26c388a3">|
=> Add CIS 1.8

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_4_11/data.yaml, bundle/compliance/cis_gcp/rules/cis_4_11/rule.rego, bundle/compliance/cis_gcp/rules/cis_4_11/test.rego, bundle/compliance/cis_gcp/rules/cis_4_8/data.yaml, bundle/compliance/cis_gcp/rules/cis_4_8/rule.rego, bundle/compliance/cis_gcp/rules/cis_4_8/test.rego, bundle/compliance/cis_gcp/rules/cis_4_9/data.yaml, bundle/compliance/cis_gcp/rules/cis_4_9/rule.rego, bundle/compliance/cis_gcp/rules/cis_4_9/test.rego, bundle/compliance/policy/gcp/common.rego
Implement rules 4.8, 4.9, 4.11
- Related: https://github.com/elastic/csp-security-policies/issues/241
=> [CIS GCP] Implement compute rules: 4.8, 4.9, 4.11

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_1_17/data.yaml, bundle/compliance/cis_gcp/rules/cis_1_17/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_17/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 1.17
| failed (doesn't have user encrypted key) |  passed (has a user encrypted key)  |
| <img width="831" alt="Screenshot 2023-08-08 at 17 02 44" src="https://github.com/elastic/csp-security-policies/assets/20814186/88c7019b-15a6-4154-bd2e-cf5fb18f6916"> | <img width="684" alt="Screenshot 2023-08-08 at 17 02 27" src="https://github.com/elastic/csp-security-policies/assets/20814186/c5fa1dba-c108-4b9f-b3d4-9f69b6e067d3">|
=> Add CIS GCP 1.17

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_6_7/data.yaml, bundle/compliance/cis_gcp/rules/cis_6_7/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_7/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 6.7
| failed (backups are not enabled) |  passed (backups are enabled)  |
| - | <img width="307" alt="Screenshot 2023-08-09 at 9 58 38" src="https://github.com/elastic/csp-security-policies/assets/20814186/ddef1136-8bc6-4c09-b1e8-332a9edd5f33"> |
- https://github.com/elastic/csp-security-policies/issues/245
=> Add CIS GCP 6.7

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_6_4/data.yaml, bundle/compliance/cis_gcp/rules/cis_6_4/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_4/test.rego
Adds CIS GCP 6.4 
| failed (ssl is not required) |  passed (ssl is required)  |
| <img width="272" alt="Screenshot 2023-08-09 at 9 34 39" src="https://github.com/elastic/csp-security-policies/assets/20814186/6d71fb1a-1288-47be-bef4-2a3c1b492b77"> | - |
- https://github.com/elastic/csp-security-policies/issues/245
=> Add CIS GCP 6.4

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_6_6/data.yaml, bundle/compliance/cis_gcp/rules/cis_6_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_6/test.rego
Adds CIS GCP 6.6
| failed (some IP is public) |  passed (all IPs is private)  |
| <img width="339" alt="Screenshot 2023-08-09 at 9 48 21" src="https://github.com/elastic/csp-security-policies/assets/20814186/f5aa8d33-9c00-4166-a9b8-946559d52074"> | - |
- https://github.com/elastic/csp-security-policies/issues/245
=> Add CIS GCP 6.6

bundle/compliance/cis_gcp/rules/cis_1_15/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_4/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_6/rule.rego, bundle/compliance/cis_gcp/rules/cis_1_7/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_4/rule.rego
=> Tidy up rules formatting

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_6_5/data.yaml, bundle/compliance/cis_gcp/rules/cis_6_5/rule.rego, bundle/compliance/cis_gcp/rules/cis_6_5/test.rego
Adds CIS GCP 6.5
| failed (publicly accessible) |  passed (public access not defined)  |
| <img width="1020" alt="Screenshot 2023-08-10 at 12 52 32" src="https://github.com/elastic/csp-security-policies/assets/20814186/71e18433-f766-4db8-95b9-7d0a41c66980"> | - |
- https://github.com/elastic/csp-security-policies/issues/245
=> Add CIS GCP 6.5

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_3_8/data.yaml, bundle/compliance/cis_gcp/rules/cis_3_8/rule.rego, bundle/compliance/cis_gcp/rules/cis_3_8/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 3.8
| failed  |  passed   |
| ![Screenshot 2023-08-15 at 13 29 26](https://github.com/elastic/csp-security-policies/assets/20814186/c9e3e445-10f3-4aba-aec6-adc52ac368de) | - |
- https://github.com/elastic/csp-security-policies/issues/243
=> Add CIS GCP 3.8

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_2_3/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_3/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_3/test.rego, bundle/compliance/policy/gcp/data_adapter.rego
Failed:<img width="848" alt="Screenshot 2023-09-07 at 15 53 38" src="https://github.com/elastic/csp-security-policies/assets/68195305/92ece201-41c7-4d62-bec2-5b621d318f4d">
Passed:<img width="857" alt="Screenshot 2023-09-07 at 15 53 48" src="https://github.com/elastic/csp-security-policies/assets/68195305/02518381-2242-420e-a325-7ac130c6c6c4">
- Related: https://github.com/elastic/csp-security-policies/issues/250
=> [CIS GCP] Add logging rule 2.3

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_2_13/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_13/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_13/test.rego, bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego
Implement rule 2.13
- Related: https://github.com/elastic/csp-security-policies/issues/305
- Related: https://github.com/elastic/cloudbeat/pull/1340
=> [CIS GCP] Implement rule 2.13 - cloud asset inventory

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_3_2/data.yaml, bundle/compliance/cis_gcp/rules/cis_3_2/rule.rego, bundle/compliance/cis_gcp/rules/cis_3_2/test.rego
Implement rule 3.2 - compute network
- Related: https://github.com/elastic/csp-security-policies/issues/305
=> [CIS GCP] Implement rule 3.2 - compute network

README.md, RULES.md, bundle/compliance/cis_gcp/rules/cis_2_1/data.yaml, bundle/compliance/cis_gcp/rules/cis_2_1/rule.rego, bundle/compliance/cis_gcp/rules/cis_2_1/test.rego, bundle/compliance/cis_gcp/test_data.rego, bundle/compliance/policy/gcp/data_adapter.rego
Adds CIS GCP 2.1
| failed  |  passed   |
| <img width="1023" alt="Screenshot 2023-09-21 at 17 46 39" src="https://github.com/elastic/csp-security-policies/assets/20814186/69da8eb3-a334-43a5-ad69-c7452728d3a4"> | <img width="1197" alt="Screenshot 2023-09-21 at 17 45 06" src="https://github.com/elastic/csp-security-policies/assets/20814186/aa8610b6-03ba-4916-a85c-6d5195a12c0f"> |
- closes https://github.com/elastic/csp-security-policies/issues/305
=> Add CIS GCP 2.1

README.md, RULES.md, bundle/compliance/cis_azure/rules/cis_9_4/data.yaml, bundle/compliance/cis_azure/rules/cis_9_4/rule.rego, bundle/compliance/cis_azure/rules/cis_9_4/test.rego, bundle/compliance/cis_azure/test_data.rego, bundle/compliance/policy/azure/data_adapter.rego
adds CIS Azure 9.4 
- https://github.com/elastic/cloudbeat/pull/1376
=> [Azure] Add cis azure 9.4

RULES.md, bundle/compliance/cis_azure/rules/cis_3_9/data.yaml, bundle/compliance/cis_azure/rules/cis_3_9/rule.rego, bundle/compliance/cis_azure/rules/cis_3_9/test.rego, bundle/compliance/policy/azure/storage_account/ensure_service.rego
Implemented rule 3.9 from the Azure benchmark
- Related: https://github.com/elastic/cloudbeat/issues/1254
=> Implement CIS Azure rule 3.9

README.md, RULES.md, bundle/compliance/cis_azure/rules/cis_7_1/data.yaml, bundle/compliance/cis_azure/rules/cis_7_1/rule.rego, bundle/compliance/cis_azure/rules/cis_7_1/test.rego, bundle/compliance/policy/azure/data_adapter.rego
Ensure an Azure Bastion Host Exists (Automated)
- Related: https://github.com/elastic/cloudbeat/issues/1258
- Depends on: https://github.com/elastic/cloudbeat/pull/1385
=> CIS Azure: Implement 7.1

README.md, RULES.md, bundle/compliance/cis_azure/rules/cis_7_2/data.yaml, bundle/compliance/cis_azure/rules/cis_7_2/rule.rego, bundle/compliance/cis_azure/rules/cis_7_2/test.rego, bundle/compliance/cis_azure/rules/cis_7_3/data.yaml, bundle/compliance/cis_azure/rules/cis_7_3/rule.rego, bundle/compliance/cis_azure/rules/cis_7_3/test.rego, bundle/compliance/cis_azure/rules/cis_7_4/test.rego, bundle/compliance/cis_azure/test_data.rego, bundle/compliance/policy/azure/data_adapter.rego
Ensure Virtual Machines are utilizing Managed Disks
I can't test failure E2E because when creating a VM without a managed disk, the option is disabled:
> Availability zone requires managed disks.
- Related: https://github.com/elastic/cloudbeat/issues/1258
=> CIS Azure: Implement 7.2, 7.3

README.md, RULES.md, bundle/compliance/cis_azure/rules/cis_8_5/data.yaml, bundle/compliance/cis_azure/rules/cis_8_5/rule.rego, bundle/compliance/cis_azure/rules/cis_8_5/test.rego, bundle/compliance/policy/azure/data_adapter.rego
Adding implementation for vault rule 8.5
=> Implement vault rule 8.5

bundle/compliance/cis_azure/rules/cis_7_1/test.rego, bundle/compliance/cis_azure/rules/cis_7_2/test.rego, bundle/compliance/cis_azure/rules/cis_7_3/test.rego, bundle/compliance/cis_azure/rules/cis_7_4/test.rego, bundle/compliance/cis_azure/test_data.rego, bundle/compliance/policy/azure/data_adapter.rego
Use the correct type and subtype as expected by Kibana
- Related: https://github.com/elastic/cloudbeat/pull/1392
- Related: https://github.com/elastic/cloudbeat/issues/1378
=> CIS Azure: Change type for subType
